# Generated by Django 2.1.3 on 2018-11-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='feed.HashTag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'development'), ('ps', 'personal')], default='dv', max_length=2),
        ),
    ]
